name = "MTR-LX"
author = "xingteh"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2e3153d7000e9abd80ef75f0f139bf31890266048e44bf1bf1cbcf5dca1b486e"

[versions]
fabric = "0.15.6"
minecraft = "1.19.2"
