name = "MTR-LX"
author = "xingteh"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df8f94f8cedd80c32864857fa473c94e36a144f649606ba857ab20bb80d1c518"

[versions]
fabric = "0.15.6"
minecraft = "1.19.2"
